# Generated by Django 2.2 on 2019-12-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeepLearningForum', '0002_auto_20191228_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='desc',
            field=models.CharField(default='这个人很懒，还没有留下简介哦', max_length=50, verbose_name='个人简介'),
        ),
    ]
