# Generated by Django 2.2 on 2019-12-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeepLearningForum', '0003_user_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_num',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='comment',
            name='like_num',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
