# Generated by Django 2.2 on 2019-12-30 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeepLearningForum', '0004_auto_20191229_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DeepLearningForum.Comment', verbose_name='父级评论'),
        ),
    ]
