# Generated by Django 2.2 on 2019-12-30 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeepLearningForum', '0005_auto_20191230_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='DeepLearningForum.Comment', verbose_name='子评论对象'),
        ),
    ]
