# Generated by Django 2.2 on 2019-12-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeepLearningForum', '0007_remove_comment_rid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followed_num',
            field=models.IntegerField(default=0, verbose_name='多少人关注'),
        ),
        migrations.AddField(
            model_name='user',
            name='follower_num',
            field=models.IntegerField(default=0, verbose_name='关注人数'),
        ),
    ]
