# Generated by Django 2.2 on 2019-12-31 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeepLearningForum', '0008_auto_20191231_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
    ]
