# Generated by Django 2.2 on 2020-01-01 13:51

import DeepLearningForum.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeepLearningForum', '0009_auto_20191231_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='img/avatar/default.png', max_length=200, storage=DeepLearningForum.storage.ImageStorage(), upload_to='img/avatar/%Y/%m', verbose_name='用户头像'),
        ),
    ]
